version: '3.8'
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
  api-server:
    image: api-server
    build: ./server/
    stdin_open: true
    ports: 
      - "8800:8800"
    volumes:
      - ./server:/app
      - /app/node_modules
 
